### ISSUE TITLE
ModuleNotFoundError: No module named 'correlation_cuda'

### ISSUE THREAD

**Issue by g031s066Goto** [OpenCalib/LiDAR2camera_self-check#2]
Hello.
I implemented it according to README.md, but when I tried to run Evaluation and Train, I got the following error.

Traceback (most recent call last):
  File "evaluate_calib.py", line 33, in <module>
    from models. LCCNet import LCCNet
  File "/home/user/L2c/LiDAR2camera_self-check-master/models/LCCNet.py", line 33, in <module>
    from models.correlation_package.correlation import Correlation
  File "/home/user/L2c/LiDAR2camera_self-check-master/models/correlation_package/correlation.py", line 4, in <module>
    import correlation_cuda
ModuleNotFoundError: No module named 'correlation_cuda'

Could you tell me how to deal with it?

**Comment by g031s066Goto** [comment]
After running setup.py, I got the following output:

running install
running bdist_egg
running egg_info
writing correlation_cuda.egg-info/PKG-INFO
writing dependency_links to correlation_cuda.egg-info/dependency_links.txt
writing top-level names to correlation_cuda.egg-info/top_level.txt
reading manifest file 'correlation_cuda.egg-info/SOURCES.txt'
writing manifest file 'correlation_cuda.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-3.6/correlation_cuda.cpython-36m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
creating stub loader for correlation_cuda.cpython-36m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/correlation_cuda.py to correlation_cuda.cpython-36.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying correlation_cuda.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying correlation_cuda.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying correlation_cuda.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying correlation_cuda.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
__pycache__.correlation_cuda.cpython-36: module references __file__
creating 'dist/correlation_cuda-0.0.0-py3.6-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing correlation_cuda-0.0.0-py3.6-linux-x86_64.egg
creating /home/user/anaconda3/envs/L2c/lib/python3.6/site-packages/correlation_cuda-0.0.0-py3.6-linux-x86_64.egg
Extracting correlation_cuda-0.0.0-py3.6-linux-x86_64.egg to /home/user/anaconda3/envs/L2c/lib/python3.6/site-packages
Adding correlation-cuda 0.0.0 to easy-install.pth file

Installed /home/user/anaconda3/envs/L2c/lib/python3.6/site-packages/correlation_cuda-0.0.0-py3.6-linux-x86_64.egg
Processing dependencies for correlation-cuda==0.0.0
Finished processing dependencies for correlation-cuda==0.0.0


However, when I do Evaluation and Train again, the following error occurs.

Traceback (most recent call last):
  File "evaluate_calib.py", line 33, in <module>
    from models. LCCNet import LCCNet
  File "/home/user/L2c/LiDAR2camera_self-check-master/models/LCCNet.py", line 33, in <module>
    from models.correlation_package.correlation import Correlation
  File "/home/user/L2c/LiDAR2camera_self-check-master/models/correlation_package/correlation.py", line 4, in <module>
    import correlation_cuda
ImportError: libtorch.so: cannot open shared object file: No such file or directory

Could you tell me how to deal with it?

**Comment by tanktan5460** [comment]
Did you solve the problem?
